import XCTest
import FreezeRay
@testable import FreezeRayTestApp

/// FreezeRay CLI tests
/// These tests are invoked by the FreezeRay CLI to generate frozen fixtures
final class FreezeRayTests: XCTestCase {

    // Tests are dynamically generated by the CLI
    // The CLI will create FreezeSchemaV{version}_Test.swift files in this folder
    // which will be automatically compiled thanks to folder references
}
