// AUTO-GENERATED by FreezeRay CLI
// This file is scaffolded once and owned by you. Customize as needed.
//
// Purpose: Verify that the frozen schema v2.0.0 hasn't drifted
// Generated by: freezeray freeze 2.0.0

import Testing
import FreezeRay
@testable import FreezeRayTestApp

/// Drift test for AppSchemaV2 v2.0.0
///
/// This test verifies that the current schema definition matches the frozen fixture.
/// If this test fails, it means the schema has been modified since it was frozen.
@Test("AppSchemaV2 v2.0.0 has not drifted")
func testAppSchemaV2_2_0_0_Drift() throws {
    // Call the macro-generated check function
    try AppSchemaV2.__freezeray_check_2_0_0()

    // TODO: Add custom data validation here
    // Example:
    // - Verify specific model properties exist
    // - Check relationship configurations
    // - Validate index definitions
}
